### ISSUE TITLE
proxy server

### ISSUE THREAD

**Issue by peyman1959** [sajad-sadra/dns-proxy-iran-sanction#3]
hi
Which proxy server do you recommend?
and is it okay to install both this project and the proxy server on the same VPS?

**Comment by sajad-sadra** [comment]
Hi.
I use Nginx. 
I also have an Nginx config and a container image for this purpose([see this repo](https://github.com/sajad-sadra/proxy-pass-http-and-https)).

yes, it's okay to set up both of them on the same server.
